# Association Rules.

### Objective :
The Objective of this assignment is to introduce and understanding to rule mining techniques, particularly focusing on market basket analysis and provide hands on experience.

### Task-1 Data Preprocessing :
Pre-process the dataset to ensure it is suitable for Association rules, this may include handling missing values, removing duplicates, and converting the data to appropriate format.

In [1]:
# import the required libraries.
import pandas as pd
import warnings

In [2]:
# Load and read the given dataset
warnings.simplefilter('ignore')
data=pd.read_excel('Online retail.xlsx')

In [3]:
data.head()

  shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                             burgers,meatballs,eggs
1                                            chutney
2                                     turkey,avocado
3  mineral water,milk,energy bar,whole wheat rice...
4                                     low fat yogurt

In [4]:
data

     shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                                burgers,meatballs,eggs
1                                               chutney
2                                        turkey,avocado
3     mineral water,milk,energy bar,whole wheat rice...
4                                        low fat yogurt
...                                                 ...
7495                      butter,light mayo,fresh bread
7496  burgers,frozen vegetables,eggs,french fries,ma...
7497                                            chicken
7498                                 escalope,green tea
7499    eggs,frozen smoothie,yogurt cake,low fat yogurt

[7500 rows x 1 columns]

In [5]:
# Handling Missing Values.
data.dropna(inplace=True)

In [6]:
data.head(10)

  shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                             burgers,meatballs,eggs
1                                            chutney
2                                     turkey,avocado
3  mineral water,milk,energy bar,whole wheat rice...
4                                     low fat yogurt
5                     whole wheat pasta,french fries
6                           soup,light cream,shallot
7              frozen vegetables,spaghetti,green tea
8                                       french fries
9                                      eggs,pet food

In [7]:
# Removing Duplicate Rows
data.drop_duplicates(inplace=True)

In [8]:
data.head(20)

   shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                              burgers,meatballs,eggs
1                                             chutney
2                                      turkey,avocado
3   mineral water,milk,energy bar,whole wheat rice...
4                                      low fat yogurt
5                      whole wheat pasta,french fries
6                            soup,light cream,shallot
7               frozen vegetables,spaghetti,green tea
8                                        french fries
9                                       eggs,pet food
10                                            cookies
11      turkey,burgers,mineral water,eggs,cooking oil
12                        spaghetti,champagne,cookies
13                               mineral water,salmon
14                                      mineral water
15  shrimp,chocolate,chicken,honey,oil,cooking oil...
16                                        turkey,eggs
17  turkey,fresh tuna,tomatoes,spaghetti,mineral w...
18      meatballs,milk,honey,french fries,protein bar
19  red wine,shrimp,pasta,pepper,eggs,chocolate,sh...

#### Converting the Data into Appropriate format.

In [9]:
data.columns=['Items']

In [10]:
# Splitting the Items into Lists.
trans=data['Items'].str.split(',').apply(lambda x:[item.strip() for item in x if item])

In [12]:
!pip install scipy mlxtend

Requirement already satisfied: scipy in c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages (1.17.1)
Collecting mlxtend
  Using cached mlxtend-0.24.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: numpy<2.7,>=1.26.4 in c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages (from scipy) (2.4.4)
Requirement already satisfied: pandas>=2.3.3 in c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages (from mlxtend) (3.0.1)
Requirement already satisfied: scikit-learn>=1.8.0 in c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages (from mlxtend) (1.8.0)
Requirement already satisfied: matplotlib>=3.10.8 in c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages (from mlxtend) (3.10.8)
Requirement already satisfied: joblib>=1.5.2 in c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (26.0)
Requirement already satisfied: pillow>=8 in c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.3)
Requirement already satisfied: six>=1.5 in c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Using cached mlxtend-0.24.0-py3-none-any.whl (1.4 MB)
Installing collected packages: mlxtend
Successfully installed mlxtend-0.24.0

WARNING: Ignoring invalid distribution ~andas (c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~andas (c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~andas (c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~andas (c:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages)

In [13]:
# Converting to One-Hot Encoding format.
from mlxtend.preprocessing import TransactionEncoder
Te=TransactionEncoder()
data_Te=Te.fit(trans).transform(trans)
df=pd.DataFrame(data_Te,columns=Te.columns_)

In [14]:
data.head(20)

                                                Items
0                              burgers,meatballs,eggs
1                                             chutney
2                                      turkey,avocado
3   mineral water,milk,energy bar,whole wheat rice...
4                                      low fat yogurt
5                      whole wheat pasta,french fries
6                            soup,light cream,shallot
7               frozen vegetables,spaghetti,green tea
8                                        french fries
9                                       eggs,pet food
10                                            cookies
11      turkey,burgers,mineral water,eggs,cooking oil
12                        spaghetti,champagne,cookies
13                               mineral water,salmon
14                                      mineral water
15  shrimp,chocolate,chicken,honey,oil,cooking oil...
16                                        turkey,eggs
17  turkey,fresh tuna,tomatoes,spaghetti,mineral w...
18      meatballs,milk,honey,french fries,protein bar
19  red wine,shrimp,pasta,pepper,eggs,chocolate,sh...

In [15]:
df.head(10)

,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,body spray,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

Collecting scipy
  Using cached scipy-1.17.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting mlxtend
  Using cached mlxtend-0.24.0-py3-none-any.whl.metadata (7.3 kB)
Collecting numpy<2.7,>=1.26.4 (from scipy)
  Using cached numpy-2.4.4-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting pandas>=2.3.3 (from mlxtend)
  Using cached pandas-3.0.1-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting matplotlib>=3.10.8 (from mlxtend)
  Using cached matplotlib-3.10.8-cp313-cp313-win_amd64.whl.metadata (52 kB)
Collecting contourpy>=1.0.1 (from matplotlib>=3.10.8->mlxtend)
  Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib>=3.10.8->mlxtend)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib>=3.10.8->mlxtend)
  Using cached fonttools-4.62.1-cp313-cp313-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib>=3.10.8->mlxtend)
  Using cached kiwisolver-1.5.0-cp313-cp313-win_amd64.whl.metadata (5.2 kB)
Collecting packaging>=20.0 (from matplotlib>=3.10.8->mlxtend)
  Using cached packaging-26.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pillow>=8 (from matplotlib>=3.10.8->mlxtend)
  Using cached pillow-12.1.1-cp313-cp313-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib>=3.10.8->mlxtend)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting python-dateutil>=2.7 (from matplotlib>=3.10.8->mlxtend)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting tzdata (from pandas>=2.3.3->mlxtend)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Using cached scipy-1.17.1-cp313-cp313-win_amd64.whl (36.5 MB)
Using cached numpy-2.4.4-cp313-cp313-win_amd64.whl (12.3 MB)
Using cached scikit_learn-1.8.0-cp313-cp313-win_amd64.whl (8.0 MB)
Using cached mlxtend-0.24.0-py3-none-any.whl (1.4 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached matplotlib-3.10.8-cp313-cp313-win_amd64.whl (8.1 MB)
Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.62.1-cp313-cp313-win_amd64.whl (2.3 MB)
Using cached kiwisolver-1.5.0-cp313-cp313-win_amd64.whl (73 kB)
Using cached packaging-26.0-py3-none-any.whl (74 kB)
Using cached pandas-3.0.1-cp313-cp313-win_amd64.whl (9.7 MB)
Using cached pillow-12.1.1-cp313-cp313-win_amd64.whl (7.0 MB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, threadpoolctl, six, pyparsing, pillow, packaging, numpy, kiwisolver, joblib, fonttools, cycler, scipy, python-dateutil, contourpy, scikit-learn, pandas, matplotlib, mlxtend

  Attempting uninstall: tzdata

    Found existing installation: tzdata 2025.3

    Uninstalling tzdata-2025.3:

   ----------------------------------------  0/18 [tzdata]
      Successfully uninstalled tzdata-2025.3
   ----------------------------------------  0/18 [tzdata]
   ----------------------------------------  0/18 [tzdata]
   ----------------------------------------  0/18 [tzdata]
   ----------------------------------------  0/18 [tzdata]
   ----------------------------------------  0/18 [tzdata]
   ----------------------------------------  0/18 [tzdata]
   ----------------------------------------  0/18 [tzdata]
  Attempting uninstall: threadpoolctl
   ----------------------------------------  0/18 [tzdata]
    Found existing installation: threadpoolctl 3.6.0
   ----------------------------------------  0/18 [tzdata]
    Uninstalling threadpoolctl-3.6.0:
   ----------------------------------------  0/18 [tzdata]
   -- -------------------------------------  1/18 [threadpoolctl]
   -- -------------------------------------  1/18 [threadpoolctl]
   -- -------------------------------------  1/18 [threadpoolctl]
   -- -------------------------------------  1/18 [threadpoolctl]
   -- -------------------------------------  1/18 [threadpoolctl]
   -- -------------------------------------  1/18 [threadpoolctl]
   -- -------------------------------------  1/18 [threadpoolctl]
      Successfully uninstalled threadpoolctl-3.6.0
   -- -------------------------------------  1/18 [threadpoolctl]
  Attempting uninstall: six
   -- -------------------------------------  1/18 [threadpoolctl]
    Found existing installation: six 1.17.0
   -- -------------------------------------  1/18 [threadpoolctl]
    Uninstalling six-1.17.0:
   -- -------------------------------------  1/18 [threadpoolctl]
   ---- -----------------------------------  2/18 [six]
   ---- -----------------------------------  2/18 [six]
      Successfully uninstalled six-1.17.0
   ---- -----------------------------------  2/18 [six]
   ---- -----------------------------------  2/18 [six]
  Attempting uninstall: pyparsing
   ---- -----------------------------------  2/18 [six]
    Found existing installation: pyparsing 3.3.2
   ---- -----------------------------------  2/18 [six]
    Uninstalling pyparsing-3.3.2:
   ---- -----------------------------------  2/18 [six]
      Successfully uninstalled pyparsing-3.3.2
   ---- -----------------------------------  2/18 [six]
   ------ ---------------------------------  3/18 [pyparsing]
   ------ ---------------------------------  3/18 [pyparsing]
   ------ ---------------------------------  3/18 [pyparsing]
   ------ ---------------------------------  3/18 [pyparsing]
  Attempting uninstall: pillow
   ------ ---------------------------------  3/18 [pyparsing]
    Found existing installation: pillow 12.1.1
   ------ ---------------------------------  3/18 [pyparsing]
    Uninstalling pillow-12.1.1:
   ------ ---------------------------------  3/18 [pyparsing]
      Successfully uninstalled pillow-12.1.1
   ------ ---------------------------------  3/18 [pyparsing]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
   -------- -------------------------------  4/18 [pillow]
  Attempting uninstall: packaging
   -------- -------------------------------  4/18 [pillow]
    Found existing installation: packaging 26.0
   -------- -------------------------------  4/18 [pillow]
   ----------- ----------------------------  5/18 [packaging]
    Uninstalling packaging-26.0:
   ----------- ----------------------------  5/18 [packaging]
      Successfully uninstalled packaging-26.0
   ----------- ----------------------------  5/18 [packaging]
   ----------- ----------------------------  5/18 [packaging]
   ----------- ----------------------------  5/18 [packaging]
   ----------- ----------------------------  5/18 [packaging]
  Attempting uninstall: numpy
   ----------- ----------------------------  5/18 [packaging]
    Found existing installation: numpy 2.4.4
   ----------- ----------------------------  5/18 [packaging]
   ------------- --------------------------  6/18 [numpy]
    Uninstalling numpy-2.4.4:
   ------------- --------------------------  6/18 [numpy]
      Successfully uninstalled numpy-2.4.4
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
   ------------- --------------------------  6/18 [numpy]
  Attempting uninstall: kiwisolver
   ------------- --------------------------  6/18 [numpy]
    Found existing installation: kiwisolver 1.5.0
   ------------- --------------------------  6/18 [numpy]
    Uninstalling kiwisolver-1.5.0:
   ------------- --------------------------  6/18 [numpy]
      Successfully uninstalled kiwisolver-1.5.0
   ------------- --------------------------  6/18 [numpy]
   --------------- ------------------------  7/18 [kiwisolver]
   --------------- ------------------------  7/18 [kiwisolver]
   --------------- ------------------------  7/18 [kiwisolver]
   --------------- ------------------------  7/18 [kiwisolver]
   --------------- ------------------------  7/18 [kiwisolver]
   --------------- ------------------------  7/18 [kiwisolver]
   --------------- ------------------------  7/18 [kiwisolver]
   --------------- ------------------------  7/18 [kiwisolver]
   --------------- ------------------------  7/18 [kiwisolver]
   --------------- ------------------------  7/18 [kiwisolver]
   --------------- ------------------------  7/18 [kiwisolver]
   --------------- ------------------------  7/18 [kiwisolver]
   --------------- ------------------------  7/18 [kiwisolver]
   --------------- ------------------------  7/18 [kiwisolver]
   --------------- ------------------------  7/18 [kiwisolver]
   --------------- ------------------------  7/18 [kiwisolver]
   --------------- ------------------------  7/18 [kiwisolver]
   --------------- ------------------------  7/18 [kiwisolver]
  Attempting uninstall: joblib
   --------------- ------------------------  7/18 [kiwisolver]
    Found existing installation: joblib 1.5.3

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages\~il'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages\~umpy'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages\~iwisolver'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages\~cipy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages\~cipy'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages\~klearn'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Gauri\DataScience1\Assignment\.venv\Lib\site-packages\~andas'.
  You can safely remove it manually.
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'c:\\users\\gauri\\datascience1\\assignment\\.venv\\lib\\site-packages\\matplotlib\\backends\\_backend_agg.cp313-win_amd64.pyd'
Check the permissions.

### Task-2 Association Rule Mining :
1. Implement an Apriori algorithm using tool like python with libraries such as Pandas and Mlxtend etc.
2. Apply association rule mining techniques to the pre-processed dataset to discover interesting relationships between products purchased together.
3. Set appropriate threshold for support, confidence and lift to extract meaning full rules.

#### 1.Implement an Apriori algorithm using tool like python with libraries such as Pandas and Mlxtend etc.

In [16]:
# Import required libraries
from mlxtend.frequent_patterns import apriori,association_rules

In [17]:
# Applying Apriori algorith to find frequent itemsets.
freq_itemsets=apriori(df,min_support=0.01,use_colnames=True)

In [18]:
freq_itemsets.head(10)

    support                        itemsets
0  0.029179            frozenset({almonds})
1  0.011014  frozenset({antioxydant juice})
2  0.045797            frozenset({avocado})
3  0.012560              frozenset({bacon})
4  0.015459     frozenset({barbecue sauce})
5  0.020483          frozenset({black tea})
6  0.013140        frozenset({blueberries})
7  0.016232         frozenset({body spray})
8  0.045024           frozenset({brownies})
9  0.012367          frozenset({bug spray})

#### 2.Apply association rule mining techniques to the pre-processed dataset to discover interesting relationships between products purchased together.
#### 3.Set appropriate threshold for support, confidence and lift to extract meaning full rules.

In [19]:
# Generation of Association Rules.
rules=association_rules(freq_itemsets,metric="confidence",min_threshold=0.2)

In [20]:
# Filtering rules Based on Metrics.
rules=rules[rules['lift']>1.0]

In [21]:
rules[['antecedents','consequents','support','confidence','lift']]

,antecedents,consequents,support,confidence,lift
0,frozenset({almonds}),frozenset({mineral water}),0.010821,0.370861,1.237399
1,frozenset({avocado}),frozenset({chocolate}),0.010242,0.223629,1.089716
2,frozenset({avocado}),frozenset({french fries}),0.011594,0.253165,1.314069
3,frozenset({avocado}),frozenset({milk}),0.010821,0.236287,1.389528
4,frozenset({avocado}),frozenset({mineral water}),0.015845,0.345992,1.154421
...,...,...,...,...,...
350,"frozenset({spaghetti, shrimp})",frozenset({mineral water}),0.012367,0.407643,1.360125
351,"frozenset({mineral water, soup})",frozenset({spaghetti}),0.010821,0.323699,1.410054
352,"frozenset({spaghetti, soup})",frozenset({mineral water}),0.010821,0.523364,1.746235
353,"frozenset({mineral water, tomatoes})",frozenset({spaghetti}),0.013527,0.391061,1.703487
354,"frozenset({spaghetti, tomatoes})",frozenset({mineral water}),0.013527,0.451613,1.506832

In [22]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({almonds}),frozenset({mineral water}),0.029179,0.299710,0.010821,0.370861,1.237399,1.0,0.002076,1.113092,0.197619,0.034022,0.101602,0.203483
1,frozenset({avocado}),frozenset({chocolate}),0.045797,0.205217,0.010242,0.223629,1.089716,1.0,0.000843,1.023715,0.086281,0.042536,0.023165,0.136767
2,frozenset({avocado}),frozenset({french fries}),0.045797,0.192657,0.011594,0.253165,1.314069,1.0,0.002771,1.081019,0.250476,0.051107,0.074947,0.156673
3,frozenset({avocado}),frozenset({milk}),0.045797,0.170048,0.010821,0.236287,1.389528,1.0,0.003034,1.086732,0.293786,0.052780,0.079810,0.149962
4,frozenset({avocado}),frozenset({mineral water}),0.045797,0.299710,0.015845,0.345992,1.154421,1.0,0.002120,1.070766,0.140185,0.048066,0.066089,0.199430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,"frozenset({spaghetti, shrimp})",frozenset({mineral water}),0.030338,0.299710,0.012367,0.407643,1.360125,1.0,0.003274,1.182210,0.273058,0.038929,0.154126,0.224454
351,"frozenset({mineral water, soup})",frozenset({spaghetti}),0.033430,0.229565,0.010821,0.323699,1.410054,1.0,0.003147,1.139190,0.300865,0.042912,0.122183,0.185419
352,"frozenset({spaghetti, soup})",frozenset({mineral water}),0.020676,0.299710,0.010821,0.523364,1.746235,1.0,0.004624,1.469236,0.436362,0.034956,0.319374,0.279735
353,"frozenset({mineral water, tomatoes})",frozenset({spaghetti}),0.034589,0.229565,0.013527,0.391061,1.703487,1.0,0.005586,1.265209,0.427765,0.053971,0.209617,0.224992
354,"frozenset({spaghetti, tomatoes})",frozenset({mineral water}),0.029952,0.299710,0.013527,0.451613,1.506832,1.0,0.004550,1.276999,0.346742,0.042787,0.216914,0.248373

In [23]:
rules_sort=rules.sort_values(by='lift',ascending=False)

In [24]:
rules_sort[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head()

,antecedents,consequents,support,confidence,lift
176,frozenset({whole wheat pasta}),frozenset({olive oil}),0.011014,0.271429,3.100757
126,frozenset({herb & pepper}),frozenset({ground beef}),0.022802,0.343023,2.525100
312,"frozenset({mineral water, shrimp})",frozenset({frozen vegetables}),0.010435,0.312139,2.403747
303,"frozenset({spaghetti, frozen vegetables})",frozenset({ground beef}),0.012560,0.321782,2.368738
342,"frozenset({spaghetti, milk})",frozenset({olive oil}),0.010242,0.204633,2.337697

In [25]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({almonds}),frozenset({mineral water}),0.029179,0.299710,0.010821,0.370861,1.237399,1.0,0.002076,1.113092,0.197619,0.034022,0.101602,0.203483
1,frozenset({avocado}),frozenset({chocolate}),0.045797,0.205217,0.010242,0.223629,1.089716,1.0,0.000843,1.023715,0.086281,0.042536,0.023165,0.136767
2,frozenset({avocado}),frozenset({french fries}),0.045797,0.192657,0.011594,0.253165,1.314069,1.0,0.002771,1.081019,0.250476,0.051107,0.074947,0.156673
3,frozenset({avocado}),frozenset({milk}),0.045797,0.170048,0.010821,0.236287,1.389528,1.0,0.003034,1.086732,0.293786,0.052780,0.079810,0.149962
4,frozenset({avocado}),frozenset({mineral water}),0.045797,0.299710,0.015845,0.345992,1.154421,1.0,0.002120,1.070766,0.140185,0.048066,0.066089,0.199430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,"frozenset({spaghetti, shrimp})",frozenset({mineral water}),0.030338,0.299710,0.012367,0.407643,1.360125,1.0,0.003274,1.182210,0.273058,0.038929,0.154126,0.224454
351,"frozenset({mineral water, soup})",frozenset({spaghetti}),0.033430,0.229565,0.010821,0.323699,1.410054,1.0,0.003147,1.139190,0.300865,0.042912,0.122183,0.185419
352,"frozenset({spaghetti, soup})",frozenset({mineral water}),0.020676,0.299710,0.010821,0.523364,1.746235,1.0,0.004624,1.469236,0.436362,0.034956,0.319374,0.279735
353,"frozenset({mineral water, tomatoes})",frozenset({spaghetti}),0.034589,0.229565,0.013527,0.391061,1.703487,1.0,0.005586,1.265209,0.427765,0.053971,0.209617,0.224992
354,"frozenset({spaghetti, tomatoes})",frozenset({mineral water}),0.029952,0.299710,0.013527,0.451613,1.506832,1.0,0.004550,1.276999,0.346742,0.042787,0.216914,0.248373

### Task-3 Analysis and Interpretation :
1. Analyse the generated rules to identify interesting patterns and relationships between the products.
2. Interpret the results and provide insights into customer purchasing behaviour based on the discovered rules

In [26]:
print(rules_sort.head(10))

                                       antecedents  \
176                 frozenset({whole wheat pasta})
126                     frozenset({herb & pepper})
312             frozenset({mineral water, shrimp})
303      frozenset({spaghetti, frozen vegetables})
342                   frozenset({spaghetti, milk})
305    frozenset({frozen vegetables, ground beef})
337               frozenset({mineral water, soup})
188                frozenset({eggs, french fries})
328          frozenset({mineral water, spaghetti})
313  frozenset({mineral water, frozen vegetables})

                        consequents  antecedent support  consequent support  \
176          frozenset({olive oil})            0.040580            0.087536
126        frozenset({ground beef})            0.066473            0.135845
312  frozenset({frozen vegetables})            0.033430            0.129855
303        frozenset({ground beef})            0.039034            0.135845
342          frozenset({olive oil})            0.050048            0.087536
305          frozenset({spaghetti})            0.024541            0.229565
337               frozenset({milk})            0.033430            0.170048
188            frozenset({burgers})            0.046377            0.113816
328        frozenset({ground beef})            0.085024            0.135845
313             frozenset({shrimp})            0.050435            0.098744

      support  confidence      lift  representativity  leverage  conviction  \
176  0.011014    0.271429  3.100757               1.0  0.007462    1.252401
126  0.022802    0.343023  2.525100               1.0  0.013772    1.315350
312  0.010435    0.312139  2.403747               1.0  0.006094    1.265001
303  0.012560    0.321782  2.368738               1.0  0.007258    1.274155
342  0.010242    0.204633  2.337697               1.0  0.005861    1.147224
305  0.012560    0.511811  2.229480               1.0  0.006927    1.578149
337  0.012367    0.369942  2.175512               1.0  0.006682    1.317263
188  0.011401    0.245833  2.159911               1.0  0.006123    1.175050
328  0.024734    0.290909  2.141472               1.0  0.013184    1.218680
313  0.010435    0.206897  2.095283               1.0  0.005455    1.136366

     zhangs_metric   jaccard  certainty  kulczynski
176       0.706154  0.094059   0.201534    0.198628
126       0.646983  0.127018   0.239746    0.255438
312       0.604181  0.068268   0.209487    0.196248
303       0.601306  0.077381   0.215166    0.207122
342       0.602377  0.080425   0.128331    0.160815
305       0.565339  0.052000   0.366346    0.283262
337       0.559026  0.064712   0.240850    0.221335
188       0.563134  0.076623   0.148972    0.173002
328       0.582563  0.126108   0.179440    0.236493
313       0.550502  0.075209   0.120002    0.156286

### Interview Questions:
1.	What is lift and why is it important in Association rules?
2.	What is support and Confidence. How do you calculate them?
3.	What are some limitations or challenges of Association rules mining?

#### 1.What is lift and why is it important in Association rules?
Lift is a measure that helps you understand how much more likely two items are to appear together compared to if they were independent. It tells you if there's a meaningful relationship between two items or events beyond random chance.

Lift indicates how much more likely one item is found with another than by pure chance. A lift greater than 1 shows a positive association (the items often appear together), while a lift less than 1 suggests a negative association (they rarely appear together). A lift of exactly 1 implies no relationship.

#### 2.What is support and Confidence. How do you calculate them?
Support measures how frequently an item or a combination of items appears in the dataset. It’s a measure of the general frequency of occurrence, which helps in identifying common itemsets.

Formula: Support(𝐴→𝐵)=Transactions containing 𝐴 and 𝐵/Total transactions​

Confidence is a measure of how often items in an association rule are found together. Specifically, it measures the likelihood of finding item B in a transaction if item A is already present.

Formula: Confidence(𝐴→𝐵)=Transactions containing 𝐴 and 𝐵/Transactions containing 𝐴

#### 3.What are some limitations or challenges of Association rules mining?
Scalability: With large datasets, the number of possible item combinations can be enormous, leading to high computational costs.

Threshold Selection: Setting support and confidence thresholds is tricky. Too low, and you get an overwhelming number of rules; too high, and you might miss potentially useful associations.

Relevancy: Not all discovered rules are useful or interesting; filtering out trivial or irrelevant rules can be challenging.